#!/usr/bin/env bash
# /root/.bin/Gentoo/e - portage management tool

#Test if user is root
if [ "$(id -u 2>/dev/null)" != "0" ]; then
  echo "ERROR: $0 must be run as root" >&2
  exit 1
fi

package_use="/etc/portage/package.use"
package_keywords="/etc/portage/package.keywords"
package_mask="/etc/portage/package.mask"
package_unmask="/etc/portage/package.unmask"

category=$(eix -en# "$@" | cut -d" " -f1 | sed -e 's/^[<>=]*//' -e 's/\/.*//')
#package=$(eix -en# "$@" | cut -d" " -f1 | sed  -e 's/^[<>=]*[a-z]*\-[a-z]*\///' -e 's/\-[0-9].*$//')

if [[ -z $@ ]]; then
  echo "e <option> <*option2/pkg> - portage management tasks:
  1 | oneshot   - adds a package as a dependency
  - | flagrem   - removes a global USE flag
  + | flagadd   - adds a global USE flag
  b | blocked   - blocked pkg workaround - <blocking> <tomerge>
  c | clean     - cleans (removes) package sources no longer in portage tree
  d | depclean  - remove unneeded dependencies
  e | elog      - view elog (developer notes for merged packages)
  f | flag      - add flag to package - <category/pkg flag>
  g | flaginfo  - information on a package's USE flags
  h | flaghas   - programs using USE flag
  i | install   - installs package (will use binary if available)
  k | keyword   - add keyword for unsupport archtechtures
  l | list      - lists files installed to a package
  m | manifest  - generate and sign all manifest in <overlay>
  o | owns      - check the file's owning package
  p | pretend   - check details of how a package is going to be added
  q | query     - search for an installed package
  r | remove    - remove package(s)
  s | search    - search for a package
  t | searchdes - search the description of packages
  u | upgrade   - emerge @world (upgrade everything)
  x | check     - check installed pkg(s) integrity
  y | sync      - sync the portage database
  z | revdep    - rebuild dependencies
  freeze        - freeze a pkg update - <cat/pkg> <cat/pkg-version>
  unfreeze      - unfreeze a package - <package>
  unmask        - unmask package - <category/pkg-*version>
  gcl           - list installed gcc compilers
  gcs           - set new gcc compiler
  kl            - list available kernels
  ks            - select new kernel (will require bootloader update)"
  exit
fi

# change to ebuild directory, put in ~/.bashrc:
# cde () { cd "$(dirname `equery ewhich "$@"`)" ; }
# b | blocked   - untested
# unfreeze      - generic matching will delete any line that matches
# forcerm(add?) - removes package that can't otherwise be uninstalled
#    forcerm )           shift
#                        emerge --force "$@"
#                        ;;
# etc-update (add?)
# --resume --skipfirst (add?)

case "$1" in
    1 | oneshot )       shift
                        emerge --oneshot "$@"
                        ;;
    - | flagrem )       shift
                        if [[ -z "$@" ]]; then
                          echo " exiting: flag required"
                          exit; else
                          euse -D "$@"
                        fi
                        ;;
    + | flagadd )       shift
                        if [[ -z "$@" ]]; then
                          echo " exiting: flag required"
                          exit; else
                          euse -E "$@"
                        fi
                        ;;
    B | Block )         shift
                        quickpkg $1
                        emerge --unmerge $1
                        emerge $2
                        emerge --usepkgonly --nodeps $1
                        ;;
    c | clean )         eclean distfiles
                        ;;
    d | depclean )      emerge --depclean
                        ;;
    e | elog )          less /var/log/portage/elog/summary.log
                        ;;
    f | flag )          shift
                        [ -r "${package_use}" ] && echo "$@" >> "${package_use}"
                        [ -d "${package_use}" ] && echo "$@" >> "${package_use}/${category}"
                        ;;
    g | useinfo )       shift
                        equery uses "$@"
                        ;;
    h | flaghas )       shift
                        equery hasuse "$@"
                        ;;
    i | install )       shift
                        emerge --usepkg --ask "$@"
                        ;;
    k | keyword )       shift
                        [ -r "${package_keywords}" ] && echo -e "$@ **" >> "${package_keywords}"
                        [ -d "${package_keywords}" ] && echo -e "$@ **" >> "${package_keywords}/${category}"
                        ;;
    l | ls | list )     shift
                        equery files "$@"
                        ;;
    m | manifest )      shift
                        if [ -r "/etc/portage/make.conf" ]; then
                          if [ -z "${PORTDIR}" ]; then
                            PORTDIR=$(source "/etc/portage/make.conf" 2>/dev/null ; echo ${PORTDIR})
                          fi
                        fi

                        if [ -r "/etc/layman/layman.cfg" ]; then
                          layman_base_dir=$(grep ^storage "/etc/layman/layman.cfg"|sed "s/.*:.//")
                        fi

                        if [ -z "${2}" ]; then
                          overlay_dir=$(for file in $(layman -Nl | cut -d" " -f3 | sed "/ *#/d; /^$/d"); do echo "$file" | grep -o --color=never "$1"; done)
                        else
                          echo "There is no any overlay ${2}"; exit 1
                        fi

                        base_dir="${layman_base_dir}/${overlay_dir}"

                        [ -d "${base_dir}" ] && echo "cd ${base_dir}"; cd "${base_dir}" #|| echo "There is no any ${base_dir}"; exit 1

                        echo "Prepare ebuild\`s and ChangeLog"
                        for file in $(find "${base_dir}" \( -name "*.ebuild" -o -name "ChangeLog" \)); do
                          cp "${file}" "${file}~";
                          [ -r "${PORTDIR}/header.txt" ] && echo "`cat ${PORTDIR}/header.txt`" > "${file}";
                          [ -r "${base_dir}/header.txt" ] && echo "`cat ${base_dir}/header.txt`" > "${file}";
                          echo "" >> "${file}";
                          echo "`sed '1,4d' "${file}~"`" >> "${file}";
                          rm -rf "${file}~";
                        done;

                        echo "Delete all current Manifest"
                        find "${base_dir}" -name Manifest -type f -exec rm {} \;

                        echo "Make all digest"
                        find "${base_dir}" -name \*.ebuild -type f -exec ebuild {} digest \; #> /dev/null 2>&1 \;

                        echo "Sign all Manifest"
                        echo -n "Enter the passphrase for gpg key: "
                        stty -echo
                        read PASSPHRASE
                        stty echo

                        for file in $(find "${base_dir}" -iname Manifest); do
                          gpg --yes --batch --passphrase="${PASSPHRASE}" --clearsign "${file}";
                          mv "${file}".asc "${file}"
                        done;
                        ;;
    o | own )           shift
                        equery belongs "$@"
                        ;;
    p | pretend )       shift
                        emerge -pv "$@"
                        ;;
    q | query )         shift
                        equery list "*$@*"
                        ;;
    r | remove )        shift
                        emerge --unmerge "$@"
                        ;;
    s | search )        shift
                        eix "$@"
                        ;;
    t | searchdes )     shift
                        eix -S "$@"
                        ;;
    u | upgrade )       emerge --update --newuse --deep --ask @world
                        ;;
    x | check )         shift
                        equery check "$@"
                        ;;
    y | sync )          emerge --sync #eix-sync
                        ;;
    z | revdep )        revdep-rebuild
                        ;;
    freeze )            shift
                        [ -r "${package_mask}" ] && echo "$1" >> "${package_mask}"
                        [ -r "${package_unmask}" ] && echo "$2" >> "${package_unmask}"
                        [ -d "${package_mask}" ] && echo "$1" >> "${package_mask}/${category}"
                        [ -d "${package_unmask}" ] && echo "$2" >> "${package_unmask}/${category}"
                        ;;
    unfreeze )          shift
                        [ -r "${package_mask}" ] && sed -i "/$@/d" "${package_mask}"
                        [ -r "${package_unmask}" ] && sed -i "/$@/d" "${package_unmask}"
                        [ -d "${package_mask}" ] && sed -i "/$@/d" "${package_mask}/${category}"
                        [ -d "${package_unmask}" ] && sed -i "/$@/d" "${package_unmask}/${category}"
                        ;;
    unmask )            shift
                        [ -r "${package_unmask}" ] && echo "$@" >> "${package_unmask}"
                        [ -d "${package_unmask}" ] && echo "$@" >> "${package_unmask}/${category}"
                        ;;
    gcl )               gcc-config -l
                        ;;
    gcs )               shift
                        gcc-config "$@"
                        ;;
    kl )                eselect kernel list
                        ;;
    ks )                shift
                        eselect kernel set "$@"
                        ;;
    * )                 emerge "$@"
esac
