#!/bin/sh

if [ -e /etc/portage/make.conf ] ; then
	if [ -z "${PORTDIR}" ] ; then
		PORTDIR=$(source /etc/portage/make.conf 2>/dev/null ; echo ${PORTDIR})
	fi
fi

cd ..
for file in $(find `pwd` -iname  \*.ebuild); do
	echo "${file}";
	cp "${file}" "${file}~";
	echo "`cat ${PORTDIR}/header.txt`" > "${file}";
	echo "" >> "${file}";
	echo "`sed '1,4d' "${file}~"`" >> "${file}";
	rm -rf "${file}~";
	ebuild "${file}" digest;
done;

for file in $(find `pwd` -iname  ChangeLog); do
	echo "${file}";
	cp "${file}" "${file}~";
	echo "`cat ${PORTDIR}/header.txt`" > "${file}";
	echo "" >> "${file}";
	echo "`sed '1,4d' "${file}~"`" >> "${file}";
	rm -rf "${file}~";
done;
